version: '3'
services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - app

  app:
    build: ./php
    volumes:
      - ./php:/var/www/html
